Fixes yaml by adding missing colon in final example
Fixes this yaml parsing error:

```
YAMLParseError: Implicit keys need to be on a single line at line 1, column 1:
```